# Generated by Django 4.1.1 on 2022-12-19 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='modified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
