# Generated by Django 4.1.4 on 2022-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelapp', '0002_image_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.CharField(default='Manager', max_length=50),
        ),
    ]
